### ISSUE TITLE
UX checklist

### ISSUE THREAD

**Issue by ryandabler** [ryandabler/What-Should-I#1]
- [x] Remove loading icon after result generation finished
- [x] Change text on loading page to say "Read more about it!"
- [x] Increase font-size for user messages
- [x] Rename "Reset" to "Restart"
- [x] Add a progress indicator to user input screens
- [x] Make select box cursor change on hover
- [x] Make underscores as wide as the box
- [x] Make user message cursor change on hover
- [x] Put blinking cursor in the input field

**Comment by ryandabler** [comment]
All elements completed
